### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo-nginx#38]
Hi there,

It seems the project is not maintained anymore, although many people rely on it for Nginx Piwik configuration.

If someone is interested to maintain this repository under the official umbrella of Piwik we would love to collaborate. The goals are to merge & review pull requests, and ensure the project is maintained when changes are required to ensure compatibility with the latest Piwik, for example: https://github.com/perusio/piwik-nginx/issues/37 

@perusio what do you think? Or maybe you'd still be keen to maintain the project?

Thanks all!

Matthieu
Piwik founder

**Comment by anoma** [comment]
I find it almost sureal that the official  [faq ](https://piwik.org/faq/how-to-install/#faq_116) of a project as large as piwik recommends the use of such a radical approach to setup.

All i see here are long forgotten tickets in (forgive me if I am wrong) a project abandoned since mid 2015.

It is just not good practice to use git to obliterate en masse OS configs, that is what sites-enabled and patches are for. If we must use git in this way there should be branches for minimal changes versus the authors opinion of refinements that may not be relevant to other use cases.

This issue needs to be solved by the upstream piwik team perhaps starting as far back as https://github.com/piwik/piwik/issues/2814 if they want to keep advertising nginx as `Piwik works very well on the webserver Nginx indeed!`.

Given that most of the ground work is done this would appear to be a relatively simple task for experts.

**Comment by perusio** [comment]
Salut Matthieu,
@mattab yes, I apologize for being so unresponsive. I kinda drifted away from PHP, but I still very much love and work with nginx, so yes, let me go through all the issues and address them one by one. Do you have any plan for addressing the issues in a structured manner, rather than just going in numerical order?

Merci,
Antonio

**Comment by mattab** [comment]
Hi Antonio,
Nice to hear from you. Maybe first you are able to go through the Pull Requests, and then the opened issues? It would be awesome to have most issues addressed so people can easily use and trust our official Nginx config. What do you think?

**Comment by mattab** [comment]
Hi @perusio 
Do you think it would be possible to move the repository to the official @matomo-org on Github at the address `matomo-org/nginx` ? Then we could maintain this project going forward. 
-> Would be great if you can initiate the transfer and we can proceed and merge the pending Pull Requests :+1: 
Thanks!

**Comment by perusio** [comment]
@mattab I tried the transfer and it failed, because you already have a repo with that name.

**Comment by mattab** [comment]
@perusio I've deleted our fork, could you please try again to move it? Thanks!

**Comment by perusio** [comment]
I cannot do it. Either you need to add me to your org or I cannot do it. It states I cannot create repos in your org.

**Comment by mattab** [comment]
Hi @perusio i've added to our organization. Thanks in advance

**Comment by mattab** [comment]
Thanks @perusio for migrating the project!
